// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_winget_output`, `safe_char_substring`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<List<WingetPackage>> listPackages() =>
    RustLib.instance.api.crateApiSimpleListPackages();

Future<List<WingetPackage>> listUpdatablePackages() =>
    RustLib.instance.api.crateApiSimpleListUpdatablePackages();

Future<List<WingetPackage>> searchPackages({required String query}) =>
    RustLib.instance.api.crateApiSimpleSearchPackages(query: query);

Future<bool> installPackage({required String id}) =>
    RustLib.instance.api.crateApiSimpleInstallPackage(id: id);

Future<bool> uninstallPackage({required String id}) =>
    RustLib.instance.api.crateApiSimpleUninstallPackage(id: id);

Future<bool> upgradePackage({required String id}) =>
    RustLib.instance.api.crateApiSimpleUpgradePackage(id: id);

Future<List<bool>> installPackages({required List<String> ids}) =>
    RustLib.instance.api.crateApiSimpleInstallPackages(ids: ids);

Future<void> exportPackages({
  required List<WingetPackage> packages,
  required String filePath,
}) => RustLib.instance.api.crateApiSimpleExportPackages(
  packages: packages,
  filePath: filePath,
);

Future<List<WingetPackage>> importPackages({required String filePath}) =>
    RustLib.instance.api.crateApiSimpleImportPackages(filePath: filePath);

class WingetPackage {
  final String name;
  final String id;
  final String version;
  final String? availableVersion;
  final String? source;

  const WingetPackage({
    required this.name,
    required this.id,
    required this.version,
    this.availableVersion,
    this.source,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      id.hashCode ^
      version.hashCode ^
      availableVersion.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WingetPackage &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          id == other.id &&
          version == other.version &&
          availableVersion == other.availableVersion &&
          source == other.source;
}
